### ISSUE TITLE
Presets are not saved after closing Blender

### ISSUE THREAD

**Issue by joulf** [stoatsnhoney/add-frame-range-presets-blender-addon#1]
Unfortunately the presets are not being saved persistently.

Steps I took:

- Set Frame Range in Blender Project
- Save Frame Frange Preset
- Save Blender Project, Exit Blender
- Open Blender, Open Project: No stored Presets in the List.

Great QOL Addon, thank you! Just letting you know, the presets don't seem to persist.

**Comment by stoatsnhoney** [comment]
I'm rewriting the add-on completely, and the new 1.1 Alpha fixes this.
